N = 1024;
p = 8;
l = 5;
alpha = [13 10 7 5 3];
tauOverTs = [0 5 12 30 50];
snr = 10;

Xk = genX(p, n);
Hk = genH(alpha, tauOverTs, l, n);
Yk = genY(Hk, Xk, 10 ^ (snr / 20), p);
XkHkPredict = fft(sqrt(ifft(corr(Yk, n), n) ./ n), n) .* Xk;
XkHkPredict(1) = Yk(1);
HkPredict = fft(ifft(XkHkPredict, n) .* genWindow(n / p, n) * p, n);
subplot(2,1,1);
stem(0:n-1, abs(Xk .* Hk));
hold on;
stem(0:n-1, abs(XkHkPredict));
legend("$|X(k)H(k)|$","$|X(k)H(k)|$ predict","Interpreter","latex","FontSize",16);
subplot(2,1,2);
plot(0:n-1, abs(Hk));
hold on;
plot(0:n-1, abs(HkPredict));
legend("$|H(k)|$","$|H(k)|$ predict","Interpreter","latex","FontSize",16);